=== rowlanja/Java-Code/XML Project/Info-Management-Group-19-master (1)/Info-Management-Group-19-master/events.dtd
<!DOCTYPE event_info [
  <!ELEMENT event_list (events+)>
    <!ELEMENT events (name,cost,location,start_time,end_time,scout_group+)>
    <!ELEMENT name (#PCDATA)>
    <!ATTLIST name number_of_uses CDATA #REQUIRED>
    <!ELEMENT cost (#PCDATA)>
    <!ELEMENT location (#PCDATA)>
    <!ELEMENT start_time (#PCDATA)>
    <!ATTLIST start_time time_taken CDATA #IMPLIED>
    <!ELEMENT end_time (#PCDATA)>
    <!ELEMENT scout_group (#PCDATA)>
]>

=== rowlanja/Java-Code/XML Project/Info-Management-Group-19-master (1)/Info-Management-Group-19-master/events.xml
<?xml version="1.0" ?>
<!DOCTYPE event_info SYSTEM "events.dtd">
<event_list>
  <events>
    <name number_of_uses="52">Weekly Meetings</name>
    <location>Scout Den</location>
    <cost>€250</cost>
    <start_time time_taken="2 hours">18:00, every Wednesday</start_time>
    <end_time>20:00, every Wednesday</end_time>
    <scout_group>Cub Scouts</scout_group>
    <scout_group>Venture Scouts</scout_group>
  </events>
   <events>
    <name number_of_uses="1">National Cub Challenge</name>
    <location>Portlick Scout Campsite, Glasson, Athlone, Co. Westmeath</location>
    <cost>€10000</cost> 
    <start_time time_taken="2 days">15th of June</start_time>
    <end_time>16th of June</end_time>
    <scout_group>Cub Scouts</scout_group>
  </events>
   <events>
    <name number_of_uses="1">Venture Challenge</name>
    <location>Anywhere in Ireland</location>
    <cost>€10000</cost>
    <start_time time_taken="5 days">1st of June</start_time>
    <end_time>5th of June</end_time>
    <scout_group>Venture Scouts</scout_group>
  </events>
</event_list>
