=== rowlanja/Java-Code/XML Project/Info-Management-Group-19-master (1)/Info-Management-Group-19-master/national_council.dtd
<!DOCTYPE national_council_doc[
  <!ELEMENT national_council_list (national_council+)> 
  <!ELEMENT national_council(year,location,board_director+,chief_scout,provincial_commissioner+,commissioner+)><!-- This is to repersent the national council based on the year. -->
  <!ELEMENT year (#PCDATA)>
  <!ELEMENT location (#PCDATA)>
  <!ELEMENT board_director (#PCDATA)>
  <!ATTLIST board_director position CDATA #REQUIRED>
  <!ELEMENT chief_scout (#PCDATA)>
  <!ELEMENT provincial_commissioner (#PCDATA)>
  <!ATTLIST provincial_commissioner province CDATA #REQUIRED>
  <!ELEMENT commissioner (#PCDATA)>
  <!ATTLIST commissioner scout_tier CDATA #REQUIRED>
]>

=== rowlanja/Java-Code/XML Project/Info-Management-Group-19-master (1)/Info-Management-Group-19-master/national_council.xml
<?xml version="1.0"?>
<!DOCTYPE national_council_doc SYSTEM "national_council.dtd" >
<national_council_list>
  <national_council>
    <year>2018</year>
    <location>Scouting Ireland, Larch Hill Tibradden, Dublin 16</location>
    <board_director position = "Chairperson">Adrian Tennant</board_director>
    <board_director position = "Secretary">Brian Smith</board_director>
    <board_director position = "Member">Dermot Lacey</board_director>
    <board_director position = "Member">Lisa Barnes</board_director>
    <board_director position = "Member">Mary Hogg</board_director>
    <board_director position = "Member">Ned Brennan</board_director>
    <board_director position = "Member">Pat Kidney</board_director>
    <board_director position = "Member">Paul Mannion</board_director>
    <board_director position = "Member">Peter Garrad</board_director>
    <chief_scout>Christy McCann</chief_scout>
    <provincial_commissioner province = "Dublin">Mark Blake</provincial_commissioner>
    <provincial_commissioner province = "South East">Kevin Murphy</provincial_commissioner>
    <provincial_commissioner province = "North">Kieran McCann</provincial_commissioner>
    <provincial_commissioner province = "North Eastern">Stephen Halpin</provincial_commissioner>
    <provincial_commissioner province = "Western">Joe Doherty</provincial_commissioner>
    <provincial_commissioner province = "South">Derek Long</provincial_commissioner>  
    <commissioner scout_tier = "Beaver Scouts">Ian Feighery</commissioner>
    <commissioner scout_tier = "Scouts">Úna O'Grady</commissioner>
    <commissioner scout_tier = "Cub Scouts">Eilís Molamphy</commissioner>
    <commissioner scout_tier = "Venture Scouts">Colin Keane</commissioner>
    <commissioner scout_tier = "Rover Scouts">Ruairi Nealon</commissioner>
    <commissioner scout_tier = "Sea Scouting">Gearóid Ó'Riain</commissioner>
  </national_council>
</national_council_list>
